### ISSUE TITLE
Fix the error on the transfer_input_files line

### ISSUE THREAD

**Issue by showmic09** [showmic09/MECH-892#32]

**Comment by aliinasrabadi** [comment]
I did the changes

**Comment by showmic09** [comment]
Hi @aliinasrabadi you did not send me a Pull request

**Comment by showmic09** [comment]
The HW4 asks you to make a pull request. Finish the steps of committing changes and making pull requests through the GitHub website

**Comment by aliinasrabadi** [comment]
Hi Dr. Islam,

Thanks a lot, I try to do that. I hope I do it right.

Thank you so much once again.

Best regards,
Ali
