### ISSUE TITLE
Fix all the issues with find-anagrams.sub file

### ISSUE THREAD

**Issue by showmic09** [showmic09/MECH-892#34]

**Comment by showmic09** [comment]
@NabiaShahreen can you make a PR to close this issue. I accidentally merged your PR that had the HW4 portion to it. you can just add some texts to the HW4/debug.md file and make a PR to close this issue.

**Comment by NabiaShahreen** [comment]
@showmic09, I have created a new PR to close this issue. The new PR is made on a different branch named HW4-Nabia-Shahreen-patch01. The debug.md file has been updated with additional information as requested.
